volumes:
 datafiles:

services:
 myslqdb:
  build:
   context: ../../projects/database/
   dockerfile: Dockerfile
  volumes:
    - datafiles:/var/lib/mysql
  ports:
      - "3306:3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 1234

 backend:
  build:
   context: ../../projects/backend
   dockerfile: Dockerfile
  depends_on:
   - myslqdb
  ports:
   - "8888:80"
  restart: always
  environment:
    - DBHOST=db
    - ASPNETCORE_ENVIRONMENT=Development