volumes:
 datafiles:

services:
 myslqdb:
  build:
   context: ../../projects/database/
   dockerfile: Dockerfile
  container_name: mysqldb
  volumes:
    - datafiles:/var/lib/mysql
  ports:
    - "3306:3306"
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: my_database

 backend:
  build:
   context: ../../projects/backend
   dockerfile: Dockerfile
  volumes:
   - datafiles:/app
  depends_on:
   - myslqdb
  ports:
   - "8888:80"
  restart: always
  environment:
    - DBHOST=db
    - ASPNETCORE_ENVIRONMENT=Development
    - MYSQL_HOST=mysql_db
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root_password
    - MYSQL_DB=my_database